// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDpJHXq3GyjG4cmP7PXKjdALpXed07gOE',
    appId: '1:633993262558:web:6b5ac538aabc962546994f',
    messagingSenderId: '633993262558',
    projectId: 'sleep-tracker-app-1751975391',
    authDomain: 'sleep-tracker-app-1751975391.firebaseapp.com',
    storageBucket: 'sleep-tracker-app-1751975391.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC74XehF-FTCZoMl-EW1x-KxzToBuFBxIE',
    appId: '1:633993262558:android:789deea2fcc4169446994f',
    messagingSenderId: '633993262558',
    projectId: 'sleep-tracker-app-1751975391',
    authDomain: 'sleep-tracker-app-1751975391.firebaseapp.com',
    storageBucket: 'sleep-tracker-app-1751975391.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDpJHXq3GyjG4cmP7PXKjdALpXed07gOE',
    appId: '1:633993262558:ios:1481d5ee488f6b7f46994f',
    messagingSenderId: '633993262558',
    projectId: 'sleep-tracker-app-1751975391',
    authDomain: 'sleep-tracker-app-1751975391.firebaseapp.com',
    storageBucket: 'sleep-tracker-app-1751975391.firebasestorage.app',
    iosBundleId: 'com.arai.sleep.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDpJHXq3GyjG4cmP7PXKjdALpXed07gOE',
    appId: '1:633993262558:ios:1481d5ee488f6b7f46994f',
    messagingSenderId: '633993262558',
    projectId: 'sleep-tracker-app-1751975391',
    authDomain: 'sleep-tracker-app-1751975391.firebaseapp.com',
    storageBucket: 'sleep-tracker-app-1751975391.firebasestorage.app',
    iosBundleId: 'com.arai.sleep.dev',
  );
}