// Mocks generated by Mockito 5.4.6 from annotations
// in sleep/test/presentation/providers/user_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter/material.dart' as _i8;
import 'package:flutter_local_notifications/flutter_local_notifications.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sleep/domain/entities/user_profile.dart' as _i6;
import 'package:sleep/domain/repositories/user_repository.dart' as _i4;
import 'package:sleep/services/notification_service.dart' as _i7;
import 'package:sleep/services/push_notification_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFlutterLocalNotificationsPlugin_0 extends _i1.SmartFake
    implements _i2.FlutterLocalNotificationsPlugin {
  _FakeFlutterLocalNotificationsPlugin_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePushNotificationService_1 extends _i1.SmartFake
    implements _i3.PushNotificationService {
  _FakePushNotificationService_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i4.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i6.UserProfile?> getUserProfile() => (super.noSuchMethod(
        Invocation.method(
          #getUserProfile,
          [],
        ),
        returnValue: _i5.Future<_i6.UserProfile?>.value(),
      ) as _i5.Future<_i6.UserProfile?>);

  @override
  _i5.Future<void> saveUserProfile(_i6.UserProfile? profile) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveUserProfile,
          [profile],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [NotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationService extends _i1.Mock
    implements _i7.NotificationService {
  MockNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FlutterLocalNotificationsPlugin get flutterLocalNotificationsPlugin =>
      (super.noSuchMethod(
        Invocation.getter(#flutterLocalNotificationsPlugin),
        returnValue: _FakeFlutterLocalNotificationsPlugin_0(
          this,
          Invocation.getter(#flutterLocalNotificationsPlugin),
        ),
      ) as _i2.FlutterLocalNotificationsPlugin);

  @override
  _i3.PushNotificationService get pushNotificationService =>
      (super.noSuchMethod(
        Invocation.getter(#pushNotificationService),
        returnValue: _FakePushNotificationService_1(
          this,
          Invocation.getter(#pushNotificationService),
        ),
      ) as _i3.PushNotificationService);

  @override
  _i5.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> requestPermissions() => (super.noSuchMethod(
        Invocation.method(
          #requestPermissions,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> scheduleBedtimeReminder({
    required _i8.TimeOfDay? bedtime,
    required int? reminderMinutes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #scheduleBedtimeReminder,
          [],
          {
            #bedtime: bedtime,
            #reminderMinutes: reminderMinutes,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> scheduleWakeUpAlarm({
    required _i8.TimeOfDay? wakeTime,
    required bool? enabled,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #scheduleWakeUpAlarm,
          [],
          {
            #wakeTime: wakeTime,
            #enabled: enabled,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> showSleepQualityNotification({
    required double? qualityScore,
    required Duration? sleepDuration,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showSleepQualityNotification,
          [],
          {
            #qualityScore: qualityScore,
            #sleepDuration: sleepDuration,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> scheduleWeeklyReport() => (super.noSuchMethod(
        Invocation.method(
          #scheduleWeeklyReport,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> cancelAllNotifications() => (super.noSuchMethod(
        Invocation.method(
          #cancelAllNotifications,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> cancelNotification(int? id) => (super.noSuchMethod(
        Invocation.method(
          #cancelNotification,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i2.PendingNotificationRequest>> getPendingNotifications() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingNotifications,
          [],
        ),
        returnValue: _i5.Future<List<_i2.PendingNotificationRequest>>.value(
            <_i2.PendingNotificationRequest>[]),
      ) as _i5.Future<List<_i2.PendingNotificationRequest>>);

  @override
  _i5.Future<void> subscribeToSleepNotifications() => (super.noSuchMethod(
        Invocation.method(
          #subscribeToSleepNotifications,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> unsubscribeFromSleepNotifications() => (super.noSuchMethod(
        Invocation.method(
          #unsubscribeFromSleepNotifications,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> subscribeToTopic(String? topic) => (super.noSuchMethod(
        Invocation.method(
          #subscribeToTopic,
          [topic],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> unsubscribeFromTopic(String? topic) => (super.noSuchMethod(
        Invocation.method(
          #unsubscribeFromTopic,
          [topic],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> sendTestPushNotification() => (super.noSuchMethod(
        Invocation.method(
          #sendTestPushNotification,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> isPushNotificationEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isPushNotificationEnabled,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
}
